// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMWAlrTWTPYqRy1OuGiPqci-XB44lI3T4',
    appId: '1:517104213699:web:dbbe61659a959c3a3bcc76',
    messagingSenderId: '517104213699',
    projectId: 'todone-ab2ca',
    authDomain: 'todone-ab2ca.firebaseapp.com',
    storageBucket: 'todone-ab2ca.firebasestorage.app',
    measurementId: 'G-T0MVM2JJ48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn3pdhk1dcJRvVnSqGDf_YUNc0Kk-7qkI',
    appId: '1:517104213699:android:9745c12f2029b0f43bcc76',
    messagingSenderId: '517104213699',
    projectId: 'todone-ab2ca',
    storageBucket: 'todone-ab2ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlkM_kjCYuSInHxUG2hgsWIyuS_ra4yVY',
    appId: '1:517104213699:ios:1c1a594cadce2aba3bcc76',
    messagingSenderId: '517104213699',
    projectId: 'todone-ab2ca',
    storageBucket: 'todone-ab2ca.firebasestorage.app',
    iosBundleId: 'com.example.todone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlkM_kjCYuSInHxUG2hgsWIyuS_ra4yVY',
    appId: '1:517104213699:ios:1c1a594cadce2aba3bcc76',
    messagingSenderId: '517104213699',
    projectId: 'todone-ab2ca',
    storageBucket: 'todone-ab2ca.firebasestorage.app',
    iosBundleId: 'com.example.todone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMWAlrTWTPYqRy1OuGiPqci-XB44lI3T4',
    appId: '1:517104213699:web:782def57b27f06c43bcc76',
    messagingSenderId: '517104213699',
    projectId: 'todone-ab2ca',
    authDomain: 'todone-ab2ca.firebaseapp.com',
    storageBucket: 'todone-ab2ca.firebasestorage.app',
    measurementId: 'G-FT5C40EFVZ',
  );
}
